// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/message/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GamerWordWatcher_WatchGamerWord_FullMethodName = "/message.GamerWordWatcher/WatchGamerWord"
)

// GamerWordWatcherClient is the client API for GamerWordWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GamerWordWatcherClient interface {
	WatchGamerWord(ctx context.Context, in *TextMessage, opts ...grpc.CallOption) (*WatcherResponse, error)
}

type gamerWordWatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewGamerWordWatcherClient(cc grpc.ClientConnInterface) GamerWordWatcherClient {
	return &gamerWordWatcherClient{cc}
}

func (c *gamerWordWatcherClient) WatchGamerWord(ctx context.Context, in *TextMessage, opts ...grpc.CallOption) (*WatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatcherResponse)
	err := c.cc.Invoke(ctx, GamerWordWatcher_WatchGamerWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamerWordWatcherServer is the server API for GamerWordWatcher service.
// All implementations must embed UnimplementedGamerWordWatcherServer
// for forward compatibility.
type GamerWordWatcherServer interface {
	WatchGamerWord(context.Context, *TextMessage) (*WatcherResponse, error)
	mustEmbedUnimplementedGamerWordWatcherServer()
}

// UnimplementedGamerWordWatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGamerWordWatcherServer struct{}

func (UnimplementedGamerWordWatcherServer) WatchGamerWord(context.Context, *TextMessage) (*WatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchGamerWord not implemented")
}
func (UnimplementedGamerWordWatcherServer) mustEmbedUnimplementedGamerWordWatcherServer() {}
func (UnimplementedGamerWordWatcherServer) testEmbeddedByValue()                          {}

// UnsafeGamerWordWatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GamerWordWatcherServer will
// result in compilation errors.
type UnsafeGamerWordWatcherServer interface {
	mustEmbedUnimplementedGamerWordWatcherServer()
}

func RegisterGamerWordWatcherServer(s grpc.ServiceRegistrar, srv GamerWordWatcherServer) {
	// If the following call pancis, it indicates UnimplementedGamerWordWatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GamerWordWatcher_ServiceDesc, srv)
}

func _GamerWordWatcher_WatchGamerWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamerWordWatcherServer).WatchGamerWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GamerWordWatcher_WatchGamerWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamerWordWatcherServer).WatchGamerWord(ctx, req.(*TextMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GamerWordWatcher_ServiceDesc is the grpc.ServiceDesc for GamerWordWatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GamerWordWatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.GamerWordWatcher",
	HandlerType: (*GamerWordWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WatchGamerWord",
			Handler:    _GamerWordWatcher_WatchGamerWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message/message.proto",
}
